### ISSUE TITLE
Turning on/off x took too long, assuming success.

### ISSUE THREAD

**Issue by RobotLimeLtd** [luisiam/homebridge-cmdswitch2#18]
Is there a way to avoid these warnings?  I get it particularly when switching a PS4 on/off via ps4-waker.

**Comment by luisiam** [comment]
Basically you can ignore that warning. I personally use the ps4-waker as well. I setup the timer there because ps4-waker usually takes too long to complete the operation. If I am using Siri, the wait time will be too long and Siri will report a failing operation. That's why the timer exists. However, even the timer expires, ps4-waker will still be running in the background to finish what it is suppose to do. Therefore, you don't need to worry about that.

**Comment by RobotLimeLtd** [comment]
After a little more research, I found that this error message in fact comes from homebridge-harmonyhub!
